@startuml main
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()
title Сводная диаграмма контейнеров

System_Boundary(system_boundary, "Агрегатор спортивных залов") {

}

@enduml
